### ISSUE TITLE
Extension button takes too much space

### ISSUE THREAD

**Issue by oktayacikalin** [adrienjoly/chrome-next-step-for-trello#91]
Having multiple extensions in Trello quickly fills up the space of the extension bar where your extension also shows up.

It would be great to reduce its space to the only possible minimum in order to give the other extensions more space and to avoid automatic line wrapping.

Thanks for this awesome ext btw!

**Comment by adrienjoly** [comment]
Thanks for the compliments and for the suggestion, Oktay!

Would you like to propose an alternative design for this button?

**Comment by oktayacikalin** [comment]
I would only show an icon and no text.
Currently I hide the whole button using ublock origin.

**Comment by adrienjoly** [comment]
There were two reasons why I had made that button that big:
- to know what mode is currently selected;
- and because new users would otherwise think that the extension was not installed properly and/or not figure out how to change the mode. (or even: not realize that there are modes)

Ideally, we could save some space by removing most of the text (if not all) of that button. That said, we would still need a way to communicate which mode is currently selected.

The only idea that I have so far on how to achieve that, is to design one icon per mode. Unfortunately, I don't have enough skills and time to do that properly myself.

=> I welcome contributions that anybody may have on this.

**Comment by oktayacikalin** [comment]
Thank you!
